"""Shared helpers used across DNScope subsystems."""

from dnscope.utils.async_utils import (
    AsyncStopwatch,
    BoundedGatherer,
    GatherError,
    RateLimiter,
    SyncRateLimiter,
    clamp,
    gather_with_limits,
    run_async,
    semaphore_from_limit,
    with_timeout,
)
from dnscope.utils.domains import (
    domain_depth,
    format_asn,
    is_ip_literal,
    is_private_ip,
    is_subdomain_of,
    labels,
    looks_like_wildcard_artifact,
    normalize_hostname,
    parent_domain,
    parse_ip,
    public_suffix_len,
    registered_domain,
    reverse_pointer,
    valid_hostname,
    wildcard_strip,
)
from dnscope.utils.files import ensure_dir, human_size, read_text, safe_filename, safe_path, write_atomic
from dnscope.utils.hashing import (
    blake2b_hex,
    canonical_json,
    config_hash,
    payload_hash,
    sha256_file,
    sha256_hex,
    truncate_hash,
)
from dnscope.utils.ids import fingerprint, new_id, short_id
from dnscope.utils.logging import get_logger, reset_logging_for_tests, setup_logging
from dnscope.utils.redact import REDACTION_PLACEHOLDER, is_sensitive_key, mask_secret, redact_mapping, redact_text
from dnscope.utils.time_utils import (
    format_duration,
    format_elapsed,
    now_utc,
    parse_duration,
    parse_interval,
    parse_timestamp,
    utc_iso,
    utc_now_iso,
    within,
)

__all__ = [
    "REDACTION_PLACEHOLDER",
    "AsyncStopwatch",
    "BoundedGatherer",
    "GatherError",
    "RateLimiter",
    "SyncRateLimiter",
    "blake2b_hex",
    "canonical_json",
    "clamp",
    "config_hash",
    "domain_depth",
    "ensure_dir",
    "fingerprint",
    "format_asn",
    "format_duration",
    "format_elapsed",
    "gather_with_limits",
    "get_logger",
    "human_size",
    "is_ip_literal",
    "is_private_ip",
    "is_sensitive_key",
    "is_subdomain_of",
    "labels",
    "looks_like_wildcard_artifact",
    "mask_secret",
    "new_id",
    "normalize_hostname",
    "now_utc",
    "parent_domain",
    "parse_duration",
    "parse_interval",
    "parse_ip",
    "parse_timestamp",
    "payload_hash",
    "public_suffix_len",
    "read_text",
    "redact_mapping",
    "redact_text",
    "registered_domain",
    "reset_logging_for_tests",
    "reverse_pointer",
    "run_async",
    "safe_filename",
    "safe_path",
    "semaphore_from_limit",
    "setup_logging",
    "sha256_file",
    "sha256_hex",
    "short_id",
    "truncate_hash",
    "utc_iso",
    "utc_now_iso",
    "valid_hostname",
    "wildcard_strip",
    "within",
    "with_timeout",
    "write_atomic",
]
